---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
type: Opaque
data:
  user: dXNlcg==  # Base64 encoded value of 'user'
  password: cGFzc3dvcmQ=  # Base64 encoded value of 'password'

---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: redis
    image: redis:latest
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: redis-secrets
          key: user
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: redis-secrets
          key: password