---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  - name: busybox
    image: busybox:latest
    volumeMounts:
    - name: shared-data
      mountPath: /data
    command: ["/bin/sh", "-c"]
    args: ["echo 'Hello, World!' > /data/index.html"]