---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels: 
    app: demo
    run: demo
spec:
  containers:
  - name: app
    image: gcr.io/prometheus-victor/demo:v1.0.0
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10